### ISSUE TITLE
Remove Stytch and Implement Custom Authentication

### ISSUE THREAD

**Issue by mit-27** [panoratech/Panora#398]
**Tasks**
- [x] Remove Stytch
- [x] Implement Custom Auth
- [x] Remove Server Side Components from NextJS to easily migrate from Next to Vite
- [x] Add functionality to create and fetch projects that are associated with the current User
- [x] Changes for Self-hosted version
- [ ] Retrieve and display connections and API keys associated with the logged-in user.
- [x] Close #372

**Comment by mit-27** [comment]
Hello @naelob and @rflihxyz, I have some questions regarding the changes require for the self-hosted version. Right now, we are already creating a dummy user in the db via seed script.

**Question**
- Do we have to provide an authentication option for self-hosted version ?

**Comment by naelob** [comment]
@mit-27 Yes we do need it. I'll update the doc so the user can log in in the selfhost iwth this dummy data.

**Comment by mit-27** [comment]
Okay, but then we do not need to provide dummy user data as auth has the option to create an account. Users can create an account and log in with email and password.

**Comment by naelob** [comment]
> @naelob Okay, but then we do not need to provide dummy user data as auth has the option to create an account. Users can create an account and log in with email and password.

yes but its better to give them dummy data to do so. In selfhost you dont want to create an account, you wanna iterate fast without losing time
